# Neural Network

In [1]:
import numpy as np
from scipy.io import loadmat

In [18]:
data = loadmat('data/ex4data1.mat')
data

{'X': array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]),
 '__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011',
 '__version__': '1.0',
 'y': array([[10],
        [10],
        [10],
        ..., 
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)}

In [16]:
X = data['X']
y_t = data['y']

In [22]:
num_labels = 10
y = np.zeros([y_t.shape[0], num_labels])
for i in range(0, y_t.shape[0]):
    if y_t[i] == 10:
        y_t[i] = 0
    y[i, y_t[i]] = 1

In [23]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [55]:
def forwardprop(X, theta1, theta2):
    a1 = np.insert(X, 0, np.ones(X.shape[0]), axis = 1)
    z2 = np.matmul(a1, theta1)
    a2 = sigmoid(z2)
    z3 = np.matmul(a2, theta2)
    h = sigmoid(z3)
    
    return a1, z2, a2, z3, h

In [27]:
def backprop()

In [28]:
x

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [50]:
q = np.array([[2], [2], [2]])

In [43]:
np.multiply(x , q)

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [49]:
q

matrix([[2],
        [2],
        [2]])

In [44]:
x1 = np.matrix(x)

In [45]:
x1

matrix([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [46]:
q = np.matrix(q)

In [47]:
q

matrix([[2],
        [2],
        [2]])

In [53]:
np.matmul(x, q)

array([[ 6.],
       [ 6.],
       [ 6.]])